import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';

@Component({selector:'app-configuracoes',imports:[FormsModule,MatIconModule],template:`
  <div class="page-head"><div><span>PERSONALIZAÇÃO</span><h1>Configurações</h1><p>Ajuste sua empresa e as regras da operação.</p></div><button (click)="saved=true"><mat-icon>save</mat-icon>{{saved?'Alterações salvas':'Salvar alterações'}}</button></div>
  <div class="layout"><nav><a class="active"><mat-icon>business</mat-icon>Empresa</a><a><mat-icon>group</mat-icon>Equipe e permissões</a><a><mat-icon>sell</mat-icon>Tipos de atendimento</a><a><mat-icon>schedule</mat-icon>Horários</a><a><mat-icon>notifications</mat-icon>Notificações</a></nav><section class="card"><h2>Dados da empresa</h2><p>Essas informações aparecem no ambiente da sua equipe.</p><div class="company"><span>CP</span><div><strong>Logo da empresa</strong><small>PNG ou JPG, até 2 MB</small><button>Alterar imagem</button></div></div><div class="two"><label>Nome da empresa<input [(ngModel)]="company" name="company"></label><label>CNPJ<input value="12.345.678/0001-90"></label></div><label>E-mail de contato<input value="contato@clinicaplena.com.br"></label><label>Endereço<input value="Av. Paulista, 1000 — São Paulo, SP"></label><hr><h2>Preferências da agenda</h2><div class="two"><label>Duração padrão<select><option>30 minutos</option><option>45 minutos</option><option>60 minutos</option></select></label><label>Intervalo entre atendimentos<select><option>Sem intervalo</option><option>10 minutos</option></select></label></div></section></div>
`,styles:[`
 .page-head{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:22px}.page-head>div>span{color:#0d9488;font-size:10px;font-weight:800;letter-spacing:1.2px}.page-head h1{font-size:27px;letter-spacing:-.7px;margin:5px 0 4px;color:#172b3d}.page-head p{margin:0;color:#8a99a8;font-size:12px}.page-head>button{height:41px;border:0;background:#0e9387;color:#fff;border-radius:9px;padding:0 14px;display:flex;align-items:center;gap:6px;font-size:10px;font-weight:750}.layout{display:grid;grid-template-columns:220px minmax(0,700px);gap:18px}.layout nav{display:grid;align-content:start;gap:4px}.layout nav a{height:42px;display:flex;align-items:center;gap:9px;border-radius:9px;padding:0 11px;color:#687988;font-size:10px}.layout nav a.active{background:#e8f7f4;color:#0d9488;font-weight:750}.layout nav .mat-icon{font-size:17px}.card{background:#fff;border:1px solid #e4eaf0;border-radius:14px;padding:24px}.card h2{font-size:14px;color:#24394b;margin:0 0 4px}.card>p{font-size:9px;color:#8b9aa7;margin:0 0 21px}.company{display:flex;align-items:center;gap:13px;margin-bottom:22px}.company>span{width:58px;height:58px;border-radius:15px;background:#dff5f1;color:#0d9488;display:grid;place-items:center;font-size:15px;font-weight:800}.company>div{display:grid;gap:3px}.company strong{font-size:10px;color:#304456}.company small{font-size:8px;color:#8b9aa7}.company button{margin-top:5px;border:0;background:transparent;color:#0d9488;font-size:9px;font-weight:750;padding:0;text-align:left}.two{display:grid;grid-template-columns:1fr 1fr;gap:13px}.card label{display:grid;gap:6px;font-size:9px;font-weight:700;color:#4b5e6f;margin-bottom:15px}.card input,.card select{height:42px;border:1px solid #dce4ea;border-radius:9px;padding:0 11px;background:#fff;font:inherit;color:#35495b}.card hr{border:0;border-top:1px solid #edf1f4;margin:11px 0 21px}@media(max-width:760px){.layout{grid-template-columns:1fr}.layout nav{display:flex;overflow:auto}.layout nav a{white-space:nowrap}.two{grid-template-columns:1fr}.page-head>button{font-size:0;width:41px;padding:0;justify-content:center}}
`]})
export class ConfiguracoesComponent{company='Clínica Plena';saved=false}
